### PR TITLE
exit with non-zero status code if run is skipped

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by s-ludwig** [comment]
Looks like the library test directories need to get a `.no_run` file in their path. I'm also thinking about changing the test runner to expect an individual `test.sh` in each directory, because building multi-package tests requires more specific invocations. We could instead extend the configurability of tests, but to me it seems like the added complexity may be worse than having a little redundancy.

**Comment by MartinNowak** [comment]
Fixed, you can already use test scripts, see #551.

**Comment by MartinNowak** [comment]
Motivation for this was that `dub dustmite` didn't complain about skipping execution.

**Comment by s-ludwig** [comment]
Ah OK good to know...

**Pull request merged**
