### PR TITLE
Proposed fix for #782

### PR DESCRIPTION
**Pull request by jeanbaptistelab**
Hi, 

here is a proposed fix for #782 which should allow using dub  with pkg-config ".pc" files for pure D shared libraries...

Cheers,

JB

### CODE REVIEW

**Comment by s-ludwig** [comment]
Just one question about the `-defaultlib` switch. Isn't that supposed to go to the D compiler instead of the linker? It doesn't seem to be handled in the test case.

**Comment by jeanbaptistelab** [comment]
I don't know, I need to look at this. Later today probably...

**Comment by jeanbaptistelab** [comment]
I've added handling of the "-pthread" option, this should also help #444 ...

**Comment by jeanbaptistelab** [comment]
Re the `-defaultlib` handling, you're right, this is a dmd option which means its "-L" (if present) needs to be stripped off so as to apply to the dmd invokation. Note (and "this may be a bad ting"™) that dmd expects the *actual* file to be given (for instance, `libphobos2.so`) while ldc seems to expect the "Unix linker" conventional name to be used (i.e. `phobos2`). I've updated my fork to pass `-defaultlib` parameters to the compiler (using the addDFlags() method), but this might not work with ldc (which would then require massaging of the actual `-defaultlib` argument...

**Comment by jeanbaptistelab** [comment]
The tests are now all green :+1:

**Comment by jeanbaptistelab** [comment]
Is there anything I should do to help this being merged ?

**Comment by s-ludwig** [comment]
Sorry, I seem to have forgotten to submit my reply earlier. So we just need to get the tests pass on all compilers. For now I think it's okay to just restrict the new test case to DMD >= 2.068. This can be done in the test script for restricting to DMD:
https://github.com/D-Programming-Language/dub/blob/e865ff2f5d5336d72ff71b4ec1ac394d3ebb9c15/test/issue613-dynlib-pic.sh#L5

And the frontend version can be restricted with a xxx.sh.min_frontend file:
https://github.com/D-Programming-Language/dub/blob/e865ff2f5d5336d72ff71b4ec1ac394d3ebb9c15/test/ddox.sh.min_frontend

**Comment by jeanbaptistelab** [comment]
I've implemented scope restrictions for #782 to DMD frontend, version >= 2.068.

**Comment by jeanbaptistelab** [comment]
Sorry about the serial commits, but it looks like this is good now...

**Comment by s-ludwig** [comment]
Okay, thanks! The diff looks good. Do you have experience with interactive rebase? It would be nice to get the commits cleaned up by squashing related changes and rebasing on top of master instead of merging. If you are not and it takes too much time, I'm not going to be pedantic about this, though ;-)

**Comment by jeanbaptistelab** [comment]
I'm not familiar with it, but I can't think of a better opportunity to learn! Let me have a crack at Google...

**Comment by jeanbaptistelab** [comment]
Ok, I think I got the gist of the rebase business, here is my proposed commit message:

    Fix and test case for issue #782. Analyze the output of pkg-config --libs <lib> and massage them if they appear to already be ready for direct use with the compiler.

    This change allows using pkg-config within dub with .pc files that were written for use with the compiler directly, which can prove troublesome in some cases (for instance, when using the GtkD debian packages as mentioned in issue #782).
    Basically, we analyze the output of pkg-config and fix up arguments so that they are suitable for the D compiler invokations through dub.
    Arguments handled include:
    - double "-L" flags (from gtkd3.pc for example) -> passed as single "-L" flags
    - "-defaultlib" flags (from phobos2.pc for example) -> passed as-is (previous dub code used to pass them as "-Ldefaultlib")
    - "-pthread" flags (from libavcode.pc for example) -> passed as "-L-l-pthread" (previous dub code used to pass them as-is)

    The test case tests for these arguments explicitly, is currently only applicable to DMD frontend versions >= 2.068 as other frontends/versions seems to have some issues with shared libraries.

**Comment by s-ludwig** [comment]
Sounds good! The test case could stay as a separate commit, but the diff is so small that it doesn't matter either way. BTW, I really like the rebase dialog of TortoiseGIT, if you are on Windows.

**Comment by jeanbaptistelab** [comment]
I'm not a fan of Windows, though when I use it, I use Emacs. Actually, I use Emacs everywhere...

**Comment by s-ludwig** [comment]
I gotta admit that I don't really use Windows either anymore, but I really do miss TortoiseGIT.

**Comment by jeanbaptistelab** [comment]
Anything else I need to do ?

**Comment by s-ludwig** [comment]
Oh sorry, I didn't realize that you already did the rebase, because all the old commits were still there.  The problem is that you probably used `git pull` after the rebased to bring your local branch up to date (which added the merge commit at the end and in turn all of the earlier commits as ancestors). Instead you need to `git push --force-with-lease` right after the rebase to overwrite the remote branch with the rebased one.

**Pull request closed without merging**
