### PR TITLE
Logging changes

### PR DESCRIPTION
**Pull request by p0nce**
PR for #608

### CODE REVIEW

**Comment by p0nce** [comment]
Bump!

**Comment by s-ludwig** [comment]
Looks good. The only thing I wonder that might still be worth to have is the "Linking..." message, so that failures can be immediately associated to either the compiler or the linker. Thoughts?

**Comment by p0nce** [comment]
Yes. It's the one I was most worried of removing.
Also having a display of the used compiler + arch one time would be great if done one time before building.

**Comment by s-ludwig** [comment]
Thinking about the latter, since the build type is also constant across all targets, that could also be moved to a single message at the beginning.

**Comment by p0nce** [comment]
Reintroduced the Linking... messages.
About the single message at beginning, this need someone more knowledgeable in the codebase.

**Comment by p0nce** [comment]
Rebased.

**Comment by s-ludwig** [comment]
Okay, thanks! I'll have a look at that message at the beginning right now.

**Pull request merged**
