### PR TITLE
replace for loops and additional filtering with partition

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
What I noticed though when this pull was done, this doesn't preserve the order of the libraries, neither does old code.

**Comment by s-ludwig** [comment]
The order should definitely be fixed in the long term, I didn't notice this in my initial implementation. But making that work in general is a little more involved, because currently three build settings fields are involved in specifying libraries (`"dflags"`, `"lflags"` and `"libs"`). We'd have to lower everything to `"dflags"` or `"lflags"`, possibly depending on the compiler.

**Comment by MartinNowak** [comment]
Can we still merge the code cleanup?

**Comment by s-ludwig** [comment]
Definitely! Forgot about that.

**Pull request merged**
