### PR TITLE
Add new 'registry' command that just open http://code.dlang.org

### PR DESCRIPTION
**Pull request by p0nce**
A way to solve #663

### CODE REVIEW

**Comment by MartinNowak** [comment]
I think the command line tool should provide the expected `dub search` functionality.
Adding a dedicated command just to browse an URL isn't justified IMO.

**Comment by p0nce** [comment]
How would a dub search command be better than opening an URL?

**Comment by s-ludwig** [comment]
Probably mostly for command-line fanatics, but since the core functionality is already there, it's an easy target. An advantage apart from working without a GUI is that the search output can be processed by a shell script to do additional things with it. Of course using the website has a lot advantages, too, and something like `dub search -web` could be an alternative if there is demand.

**Comment by p0nce** [comment]
Well, I use dub day in day out. Opening `http://code.dlang.org` is a common task.
`dub search -web` would be ok of course.

**Comment by MartinNowak** [comment]
I added the `dub search` command, so it would be easy now to make `dub search -web foobar` open http://code.dlang.org/search?q=foobar.

**Pull request closed without merging**
