### PR TITLE
Create empty DGui skeleton project

### PR DESCRIPTION
**Pull request by andre2007**
A minimal DGui application skeleton can be built

### CODE REVIEW

**Comment by Geod24** [comment]
I really think we should have a "plugin" system for that. It would mostly work by convention, so that for example, `dub init vibe.d` will look for `dub-init` folder (or subpackage) in vibe.d package, and copy it. That would also fix the issues of the packages not being in sync).

**Comment by s-ludwig** [comment]
See also my reply in #453.

**Comment by etcimon** [comment]
> I really think we should have a "plugin" system for that. It would mostly work by convention, so that for example, dub init vibe.d

A true plugin system would automatically search for and run shared libraries, and identify a set of callbacks, related or not to `init` files. This would be useful for eg. adding custom pre-processors, like a diet templates compiler that isn't CTFE but runs at compile-time.

**Comment by s-ludwig** [comment]
There are many flavors of plugin systems, it doesn't always have to be shared library based. In this particular case I think that a template package is really a much better solution. But yeah, a "build" plugin system like you describe is also something that we need to think about. I've recently talked about such possibilities with Atila Neves via e-mail and could post those in a separate ticket or on the forums.

**Comment by MartinNowak** [comment]
> See also my reply in #453.

https://github.com/D-Programming-Language/dub/pull/453#issuecomment-75568856

**Comment by blm768** [comment]
Isn't this basically a subset of the features in #600?

**Comment by s-ludwig** [comment]
@blm768: Yes, I think we should actually close this and go for a variant of #600 instead (using a sub package instead of a specific sub path).

**Pull request closed without merging**
