### PR TITLE
generate coverage report

### PR DESCRIPTION
**Pull request by MartinNowak**
- uses coveralls.io and the doveralls package

### CODE REVIEW

**Comment by MartinNowak** [comment]
depends on #549

**Comment by MartinNowak** [comment]
Disabled the somewhat annoying comments.
Preview is here https://coveralls.io/builds/2326697.

**Comment by s-ludwig** [comment]
Hm, should we merge this now, or try to get the coverage up a bit before that?

BTW, does coveralls integrate with pull requests (i.e. display an error if the coverage shrinks)?

**Comment by Geod24** [comment]
I'd say merge it now. It'll provide a nice spot to enter dub's codebase.

**Comment by MartinNowak** [comment]
Yes it does seem to integrate with pull requests, see the check above.

**Comment by MartinNowak** [comment]
> Hm, should we merge this now, or try to get the coverage up a bit before that?

Just get it merged, we can improve things on the go.

**Comment by s-ludwig** [comment]
Alright, merging in.

**Comment by MartinNowak** [comment]
Turns out coverage reports aren't merged, I disabled the pull request status API until that is fixed.
[Issue 14464 – coverage merge doesn't work](https://issues.dlang.org/show_bug.cgi?id=14464)

**Pull request merged**
