### PR TITLE
A feature like `cargo search`

### PR DESCRIPTION
**Pull request by MartinNowak**
So I've tested the Rust package manager and it has a nice feature to search available packages.

```
$ cargo search gl
Updating registry `https://github.com/rust-lang/crates.io-index`
gfx_gl (0.1.4)           OpenGL bindings for gfx, based on gl-rs
gl_common (0.0.4)        Common glue for libraries using gl-rs
gl_generator (0.0.27)    Syntax extension for creating bindings to the Khronos OpenGL and related APIs
gl (0.0.12)              OpenGL bindings
gfx_device_gl (0.5.0)    OpenGL backend for gfx-rs
glutin (0.3.5)           Cross-plaform OpenGL context provider.
kugel (0.0.2)            Rust-oriented OpenGL wrapper.
khronos_api (0.0.8)      Khronos API XML descriptions for gl_generator
freetypegl (0.1.0)       Rust build helpers and bindings for freetype-gl.
nice_glfw (1.0.1)        Create a modern GL context with glfw
```

It's also nice that it says when its package list cache is updated.

### CODE REVIEW

**Comment by MartinNowak** [comment]
Implementation done, still waiting for https://github.com/D-Programming-Language/dub-registry/pull/121 to be deployed.

**Comment by s-ludwig** [comment]
Deployment is done now.

**Comment by MartinNowak** [comment]
> Deployment is done now.

Nice, tests pass as well.

**Comment by p0nce** [comment]
Yay!

**Comment by MartinNowak** [comment]
I left-justified the package names and versions for better readability.
Now we only need a [xapian](https://github.com/D-Programming-Language/dub-registry/issues/93#issuecomment-94162874) binding for better search results ;).

**Comment by s-ludwig** [comment]
Okay, looks good.

**Comment by s-ludwig** [comment]
I added a call to `.array` to avoid the `map.filter` chain in `Dub.searchPackages` to execute the GET request multiple times.

**Pull request merged**
