### PR TITLE
Avoids duplicate dflags when calling BuildSettings.add. This avoid de…

### PR DESCRIPTION
**Pull request by p0nce**
…pendent targets from getting architecture flags from dependencies when they already have them.

### CODE REVIEW

**Comment by p0nce** [comment]
This fixes #635 , but perhaps not in the most safe way.

**Comment by p0nce** [comment]
Added the fix for #647 since such a fix would depend on this (and it's a less controversial fix).

**Comment by p0nce** [comment]
Sorry to bump this, but the fixes are working well here.
Bugs #634 and #638 combined makes LDC unusable.

**Comment by p0nce** [comment]
Added another harmless fix for LDC 0.16.x (bounds check flag was removed)

**Comment by p0nce** [comment]
@MartinNowak maybe we could discuss in https://github.com/D-Programming-Language/dub/issues/647 instead? Personally I always want a statically linked phobos.

**Comment by s-ludwig** [comment]
The redundant flags part is fixed on master now by 9a381af3bad8cafb4a63c5531ab8d85658406a4e.

**Comment by p0nce** [comment]
Thanks, will rebase this evening.

**Comment by p0nce** [comment]
Closed for reordering commits.

**Pull request closed without merging**
