### PR TITLE
DEP1: Implement SDL package description support

### PR DESCRIPTION
**Pull request by s-ludwig**
This implements [DEP1](https://github.com/D-Programming-Language/dub/wiki/DEP1) with a few fields added that are still absent from the wiki page.

### CODE REVIEW

**Comment by s-ludwig** [comment]
Wiki page is updated now.

**Comment by s-ludwig** [comment]
Since this is an additive change and all tests pass, I'd just merge this as it is. Does anyone want to have a look first? The actual change set is not as big as it looks. The "sdlang-d" commit can just be ignored for the review.

It would also be interesting to review the SDL based format to see if there is anything that could be optimized in terms of usability (see the DEP link at the top).

**Comment by grogancolin** [comment]
Just testing it out on my local branch now.
I've rewritten my local dubs dub.json to dub.sdl to see if it can parse it.

```
name "dub"
description "Package manager for D packages"
license "MIT"
copyright "Copyright © 2012-2014 rejectedsoftware e.K., Copyright © 2012-2014 Matthias Dondorff"
authors {
        "Matthias Dondorff" 
        "Sönke Ludwig"
}
targetPath "bin"

configuration {
            name "application"
            targetType "executable"
            mainSourceFile "source/app.d"
            libs "curl"
            versions "DubUseCurl"
}
configuration {
            name "library"
            targetType "library"
            excludedSourceFiles "source/app.d"
            libs "curl"
            copyFiles-windows "bin/libcurl.dll" "bin/libeay32.dll" "bin/ssleay32.dll"
            versions "DubUseCurl"
}
configuration {
            name "library-nonet"
            targetType "library"
            dependency "vibe-d" version="~>0.7.19-rc.4" optional="true"
            excludedSourceFiles "source/app.d"
}

```

It fails to parse it, throwing an unhelpful error:
```
./bin/dub                                                                                                                              
Failed to parse package description for dub  in /home/colin/Projects/dub/.
core.exception.RangeError@source/dub/recipe/sdl.d(170): Range violation
```

It would be good to add a some debug info here for the user to understand whats going wrong.

Also, this is my first time writing an SDL file, so the above may be wrong!

**Comment by s-ludwig** [comment]
The error checking code was still missing. Now outputs something along the lines of:
> Failed to load package in .../: .../dub.sdl(20): Error: Missing value for 'configuration'.

**Comment by grogancolin** [comment]
Yeah, it's much better/easier to use when the error checking is in there!

Looks good!

**Comment by s-ludwig** [comment]
Merging to master. @grogancolin Thanks for the review!

**Pull request merged**
